version: '3.4'

services:
    webapp:
        build:
            context: .
            dockerfile: RabbitMQDemo/Dockerfile
        environment:
            "ConnectionStrings:Rabbitmq": "rabbitmq"
            "ConnectionStrings:Redis": "redis"
        ports:
            - 80:80
        depends_on:
            - rabbitmq
            - redis
        restart: unless-stopped
    emailsender:
        build:
            context: .
            dockerfile: EmailSender/Dockerfile
        environment:
            "ConnectionStrings:Rabbitmq": "rabbitmq"
            "ConnectionStrings:Redis": "redis"
        depends_on:
            - rabbitmq
            - redis
        restart: unless-stopped
    rabbitmq:
        image: rabbitmq:3.9-management
        restart: unless-stopped
        volumes:
            - rabbitmqdata:/var/lib/rabbitmq/
        ports:
            - 15672:15672
            - 5672:5672
    redis:
        image: redis
        restart: unless-stopped
        volumes:
            - redisdata:/var/lib/redis
        ports:
            - 6379:6379

networks:
    mainnet:    

volumes:
    rabbitmqdata:
    redisdata: